### ISSUE TITLE
Async usage error on .NET 6

### ISSUE THREAD

**Issue by adamhathcock** [AJMitev/FileTypeChecker#15]
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq.Async, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The system cannot find the file specified.

File name: 'System.Linq.Async, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at FileTypeChecker.FileTypeValidator.GetFileTypeAsync(Stream fileContent)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at FileTypeChecker.FileTypeValidator.GetFileTypeAsync(Stream fileContent)
```

happens when only .NET 6 SDK is installed...this is from dockerized CI.

**Comment by AJMitev** [comment]
The dependancy was not included in the nuspec file. I updated the [package](https://www.nuget.org/packages/File.TypeChecker/2.0.3).
